# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d762732cf3651a8a1bbc2b022b0e7f6bb76a6eac3c6730b0c3e19af7d0d0ec0175346c760cf6d0e878dd221338beb69cb100df0ad86790f6f3b049304bde39b

test:
  secret_key_base: 1e8d863ed7a4aa2fa0b39d5c17b67378e3d4e5e36a9d73111a9fd52a636443db708c077f11a84144c9e3c0e6845184e1d9b7e2823c21886f98051119adc9a962

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
